language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cp config.example.py config.py
  # command to run tests
script:
  # Formatting compliance test
  - pytest -v
  - pycodestyle --show-source --show-pep8 --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,E402,W291 --max-line-length=300 karma/* commands/* migrations/* apollo.py models.py

# Discord notifications
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
