language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cp config.example.py config.py
  # command to run tests
script:
  # Formatting compliance test
  - pytest -v
  - black --check .
