language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cp config.example.yaml config.yaml
  - cp alembic.example.ini alembic.ini
  # command to run tests
script:
  # Formatting compliance test
  - pytest -v
  - black --check .
