version: "3"

services:
  postgres:
    image: postgres:12-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: apollo
      POSTGRES_PASSWORD: apollo
      POSTGRES_PORT: "5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    container_name: "apollo"
    build: .
    depends_on:
      - postgres
volumes:
  postgres_data:
