version: "3"

services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_USER: apollo
      POSTGRES_DB: apollo
      POSTGRES_PASSWORD: apollo
      POSTGRES_PORT: "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  apollo:
    build: .
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
        read_only: true

volumes:
  postgres_data:
