version: "3"

services:
  apollo-db:
    image: postgres:12
    environment:
      POSTGRES_USER: apollo
      POSTGRES_DB: apollo
      POSTGRES_PASSWORD: apollo
      POSTGRES_PORT: "5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apollo:
    build: .
    depends_on:
      - apollo-db
    configs:
      - source: bot-config
        target: /app/config.yaml

configs:
  bot-config:
    file: config.yaml

volumes:
  postgres_data:
