name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      SECRET_KEY: top_secret

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: apollo
          POSTGRES_PASSWORD: apollo
          POSTGRES_DB: apollo
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --user pipenv
          pipenv install --dev --deploy
          cp config.example.yaml config.yaml
          cp alembic.example.ini alembic.ini
      - name: Check formatting with isort and black
        run: |
          pipenv run isort --check-only --skip __tests__ .
          pipenv run black --check --exclude __tests__ .
      - name: Test with pytest
        if: ${{ success() || failure() }}
        run: |
          pipenv run pytest -v
      - name: Check upgrade migrations
        if: ${{ success() || failure() }}
        run: |
          pipenv run alembic upgrade head
      - name: Check downgrade migrations
        run: |
          pipenv run alembic downgrade base
