name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    env:
      SECRET_KEY: top_secret

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cp config.example.yaml config.yaml
        cp alembic.example.ini alembic.ini
    - name: Check formatting with black
      run: |
        black --check --exclude __tests__ .
    - name: Test with pytest
      run: |
        pytest -v
    - name: Check upgrade migrations
      run: |
        alembic upgrade head
    - name: Check downgrade migrations
      run: |
        alembic downgrade base
